[package]
name = "bash"
version = "0.4.0"
edition = "2024"
description = "Rust-implemented shell focused on bash compatibility"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities", "development-tools"]

[dependencies]
async-recursion = "1"
async-trait = "0"
bon = "3"
chrono = "0"
clap = { version = "4", features = ["derive", "wrap_help"] }
compio = { version = "0", default-features = false, features = [
  "macros",
  "process",
  "runtime",
  "signal",
  "time"
] }
fancy-regex = "0"
futures = "0"
git-version = "0"
indenter = "0"
indexmap = "2"
inherent = "1"
itertools = "0"

normalize-path = "0"
peg = "0"
serde = { version = "1", features = ["derive"] }

strum = "0"
strum_macros = "0"
thiserror = "2"
toml = { version = "1", default-features = false, features = [
  "parse",
  "serde",
  "std"
] }
tracing = { version = "0", default-features = false, features = ["std"] }
tracing-subscriber = { version = "0", default-features = false, features = [
  "fmt",
  "registry",
  "std"
] }
utf8-chars = "3"
windows-sys = { version = "0", features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_System_Console",
  "Win32_System_Threading",
  "Win32_UI_Input_KeyboardAndMouse"
] }

[dev-dependencies]
anyhow = "1"
insta = { version = "1", features = ["glob", "redactions", "ron", "yaml"] }
pretty_assertions = { version = "1", features = ["unstable"] }
serde_yaml = "0"
tempfile = "3"

[features]
default = []

debug-tracing = ["peg/trace"]
